### ISSUE TITLE
Remove commented code.

### ISSUE THREAD

**Issue by iadnan** [HussainShabbir/DemoCollectionView#1]
Code clean up in ViewController.swift

**Comment by iadnan** [comment]
If you have time work on UI. Add some fixed window size. When playing around with window it throws constraint warnings

**Comment by iadnan** [comment]
In swift if statements do not require brackets.

**Comment by iadnan** [comment]
Same issue with code styling, spacing issues

**Comment by HussainShabbir** [comment]
Hi Adnan,

I have fixed all the above issues. Thanks for your comments
